/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HarvestableTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aToken"
      | "baseToken"
      | "baseTokenCap"
      | "beta"
      | "collateralRatio"
      | "convertToUnwrapped"
      | "convertToWrapped"
      | "currentBaseTokenPrice"
      | "emaLeverageRatio"
      | "getCurrentNav"
      | "harvest"
      | "harvestBountyRatio"
      | "initialize"
      | "initializePrice"
      | "initializeV2"
      | "isBaseTokenPriceValid"
      | "isUnderCollateral"
      | "lastPermissionedPrice"
      | "leverageRatio"
      | "market"
      | "maxLiquidatable"
      | "maxMintableXToken"
      | "maxMintableXTokenWithIncentive"
      | "maxMintableaToken"
      | "maxRedeemableXToken"
      | "maxRedeemableaToken"
      | "mint"
      | "owner"
      | "platform"
      | "priceOracle"
      | "rateProvider"
      | "rebalancePool"
      | "rebalancePoolRatio"
      | "redeem"
      | "renounceOwnership"
      | "settleWhitelist"
      | "totalBaseToken"
      | "transferOwnership"
      | "updateBaseTokenCap"
      | "updateBeta"
      | "updateEMASampleInterval"
      | "updatePlatform"
      | "updatePriceOracle"
      | "updateRateProvider"
      | "updateRebalancePool"
      | "updateRewardRatio"
      | "updateSettleWhitelist"
      | "xAVAXLeverageRatio"
      | "xToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Harvest"
      | "OwnershipTransferred"
      | "ProtocolSettle"
      | "UpdateBaseTokenCap"
      | "UpdateBeta"
      | "UpdateEMASampleInterval"
      | "UpdatePlatform"
      | "UpdatePriceOracle"
      | "UpdateRateProvider"
      | "UpdateRebalancePool"
      | "UpdateRewardRatio"
      | "UpdateSettleWhitelist"
      | "V2Initialized"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseTokenCap",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "beta", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collateralRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertToUnwrapped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToWrapped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentBaseTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emaLeverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentNav",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "harvestBountyRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isBaseTokenPriceValid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUnderCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPermissionedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxLiquidatable",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableXToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableXTokenWithIncentive",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableaToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeemableXToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeemableaToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rebalancePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rebalancePoolRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBaseToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBaseTokenCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEMASampleInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatform",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRateProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRebalancePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardRatio",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSettleWhitelist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "xAVAXLeverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "aToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseTokenCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToUnwrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToWrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBaseTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emaLeverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentNav",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestBountyRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBaseTokenPriceValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUnderCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPermissionedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxLiquidatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableXToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableXTokenWithIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeemableXToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeemableaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalancePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalancePoolRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBaseTokenCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateBeta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateEMASampleInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRateProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRebalancePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSettleWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xAVAXLeverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xToken", data: BytesLike): Result;
}

export namespace HarvestEvent {
  export type InputTuple = [
    caller: AddressLike,
    totalRewards: BigNumberish,
    rebalancePoolRewards: BigNumberish,
    harvestBounty: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    totalRewards: bigint,
    rebalancePoolRewards: bigint,
    harvestBounty: bigint
  ];
  export interface OutputObject {
    caller: string;
    totalRewards: bigint;
    rebalancePoolRewards: bigint;
    harvestBounty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolSettleEvent {
  export type InputTuple = [price: BigNumberish, aNav: BigNumberish];
  export type OutputTuple = [price: bigint, aNav: bigint];
  export interface OutputObject {
    price: bigint;
    aNav: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateBaseTokenCapEvent {
  export type InputTuple = [baseTokenCap: BigNumberish];
  export type OutputTuple = [baseTokenCap: bigint];
  export interface OutputObject {
    baseTokenCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateBetaEvent {
  export type InputTuple = [beta: BigNumberish];
  export type OutputTuple = [beta: bigint];
  export interface OutputObject {
    beta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateEMASampleIntervalEvent {
  export type InputTuple = [sampleInterval: BigNumberish];
  export type OutputTuple = [sampleInterval: bigint];
  export interface OutputObject {
    sampleInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePlatformEvent {
  export type InputTuple = [platform: AddressLike];
  export type OutputTuple = [platform: string];
  export interface OutputObject {
    platform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePriceOracleEvent {
  export type InputTuple = [priceOracle: AddressLike];
  export type OutputTuple = [priceOracle: string];
  export interface OutputObject {
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRateProviderEvent {
  export type InputTuple = [rateProvider: AddressLike];
  export type OutputTuple = [rateProvider: string];
  export interface OutputObject {
    rateProvider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRebalancePoolEvent {
  export type InputTuple = [rebalancePool: AddressLike];
  export type OutputTuple = [rebalancePool: string];
  export interface OutputObject {
    rebalancePool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRewardRatioEvent {
  export type InputTuple = [
    rebalancePoolRatio: BigNumberish,
    harvestBountyRatio: BigNumberish
  ];
  export type OutputTuple = [
    rebalancePoolRatio: bigint,
    harvestBountyRatio: bigint
  ];
  export interface OutputObject {
    rebalancePoolRatio: bigint;
    harvestBountyRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateSettleWhitelistEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace V2InitializedEvent {
  export type InputTuple = [sampleInterval: BigNumberish];
  export type OutputTuple = [sampleInterval: bigint];
  export interface OutputObject {
    sampleInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HarvestableTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): HarvestableTreasury;
  waitForDeployment(): Promise<this>;

  interface: HarvestableTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aToken: TypedContractMethod<[], [string], "view">;

  baseToken: TypedContractMethod<[], [string], "view">;

  baseTokenCap: TypedContractMethod<[], [bigint], "view">;

  beta: TypedContractMethod<[], [bigint], "view">;

  collateralRatio: TypedContractMethod<[], [bigint], "view">;

  convertToUnwrapped: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "view"
  >;

  convertToWrapped: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "view"
  >;

  currentBaseTokenPrice: TypedContractMethod<[], [bigint], "view">;

  emaLeverageRatio: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        lastTime: bigint;
        sampleInterval: bigint;
        lastValue: bigint;
        lastEmaValue: bigint;
      }
    ],
    "view"
  >;

  getCurrentNav: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _baseNav: bigint;
        _aNav: bigint;
        _xNav: bigint;
      }
    ],
    "view"
  >;

  harvest: TypedContractMethod<[], [void], "nonpayable">;

  harvestBountyRatio: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      _market: AddressLike,
      _baseToken: AddressLike,
      _aToken: AddressLike,
      _xToken: AddressLike,
      _priceOracle: AddressLike,
      _beta: BigNumberish,
      _baseTokenCap: BigNumberish,
      _rateProvider: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initializePrice: TypedContractMethod<[], [void], "nonpayable">;

  initializeV2: TypedContractMethod<
    [sampleInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  isBaseTokenPriceValid: TypedContractMethod<[], [boolean], "view">;

  isUnderCollateral: TypedContractMethod<[], [boolean], "view">;

  lastPermissionedPrice: TypedContractMethod<[], [bigint], "view">;

  leverageRatio: TypedContractMethod<[], [bigint], "view">;

  market: TypedContractMethod<[], [string], "view">;

  maxLiquidatable: TypedContractMethod<
    [_newCollateralRatio: BigNumberish, _incentiveRatio: BigNumberish],
    [
      [bigint, bigint] & { _maxBaseOut: bigint; _maxaTokenLiquidatable: bigint }
    ],
    "view"
  >;

  maxMintableXToken: TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxXTokenMintable: bigint }],
    "view"
  >;

  maxMintableXTokenWithIncentive: TypedContractMethod<
    [_newCollateralRatio: BigNumberish, _incentiveRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxXTokenMintable: bigint }],
    "view"
  >;

  maxMintableaToken: TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxaTokenMintable: bigint }],
    "view"
  >;

  maxRedeemableXToken: TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseOut: bigint; _maxXTokenRedeemable: bigint }],
    "view"
  >;

  maxRedeemableaToken: TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseOut: bigint; _maxaTokenRedeemable: bigint }],
    "view"
  >;

  mint: TypedContractMethod<
    [_baseIn: BigNumberish, _recipient: AddressLike, _option: BigNumberish],
    [[bigint, bigint] & { _aTokenOut: bigint; _xTokenOut: bigint }],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platform: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  rateProvider: TypedContractMethod<[], [string], "view">;

  rebalancePool: TypedContractMethod<[], [string], "view">;

  rebalancePoolRatio: TypedContractMethod<[], [bigint], "view">;

  redeem: TypedContractMethod<
    [_aTokenIn: BigNumberish, _xTokenIn: BigNumberish, _owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settleWhitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  totalBaseToken: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBaseTokenCap: TypedContractMethod<
    [_baseTokenCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateBeta: TypedContractMethod<[_beta: BigNumberish], [void], "nonpayable">;

  updateEMASampleInterval: TypedContractMethod<
    [_sampleInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePlatform: TypedContractMethod<
    [_platform: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePriceOracle: TypedContractMethod<
    [_priceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRateProvider: TypedContractMethod<
    [_rateProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRebalancePool: TypedContractMethod<
    [_rebalancePool: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRewardRatio: TypedContractMethod<
    [_rebalancePoolRatio: BigNumberish, _harvestBountyRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSettleWhitelist: TypedContractMethod<
    [_account: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  xAVAXLeverageRatio: TypedContractMethod<[], [bigint], "view">;

  xToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseTokenCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beta"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateralRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToUnwrapped"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToWrapped"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentBaseTokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emaLeverageRatio"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        lastTime: bigint;
        sampleInterval: bigint;
        lastValue: bigint;
        lastEmaValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentNav"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _baseNav: bigint;
        _aNav: bigint;
        _xNav: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "harvest"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "harvestBountyRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _market: AddressLike,
      _baseToken: AddressLike,
      _aToken: AddressLike,
      _xToken: AddressLike,
      _priceOracle: AddressLike,
      _beta: BigNumberish,
      _baseTokenCap: BigNumberish,
      _rateProvider: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializePrice"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeV2"
  ): TypedContractMethod<[sampleInterval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isBaseTokenPriceValid"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUnderCollateral"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPermissionedPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "leverageRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "market"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxLiquidatable"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish, _incentiveRatio: BigNumberish],
    [
      [bigint, bigint] & { _maxBaseOut: bigint; _maxaTokenLiquidatable: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableXToken"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxXTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableXTokenWithIncentive"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish, _incentiveRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxXTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableaToken"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseIn: bigint; _maxaTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxRedeemableXToken"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseOut: bigint; _maxXTokenRedeemable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxRedeemableaToken"
  ): TypedContractMethod<
    [_newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { _maxBaseOut: bigint; _maxaTokenRedeemable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [_baseIn: BigNumberish, _recipient: AddressLike, _option: BigNumberish],
    [[bigint, bigint] & { _aTokenOut: bigint; _xTokenOut: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalancePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalancePoolRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [_aTokenIn: BigNumberish, _xTokenIn: BigNumberish, _owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleWhitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalBaseToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBaseTokenCap"
  ): TypedContractMethod<[_baseTokenCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBeta"
  ): TypedContractMethod<[_beta: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEMASampleInterval"
  ): TypedContractMethod<[_sampleInterval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatform"
  ): TypedContractMethod<[_platform: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePriceOracle"
  ): TypedContractMethod<[_priceOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRateProvider"
  ): TypedContractMethod<[_rateProvider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRebalancePool"
  ): TypedContractMethod<[_rebalancePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRewardRatio"
  ): TypedContractMethod<
    [_rebalancePoolRatio: BigNumberish, _harvestBountyRatio: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSettleWhitelist"
  ): TypedContractMethod<
    [_account: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xAVAXLeverageRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Harvest"
  ): TypedContractEvent<
    HarvestEvent.InputTuple,
    HarvestEvent.OutputTuple,
    HarvestEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolSettle"
  ): TypedContractEvent<
    ProtocolSettleEvent.InputTuple,
    ProtocolSettleEvent.OutputTuple,
    ProtocolSettleEvent.OutputObject
  >;
  getEvent(
    key: "UpdateBaseTokenCap"
  ): TypedContractEvent<
    UpdateBaseTokenCapEvent.InputTuple,
    UpdateBaseTokenCapEvent.OutputTuple,
    UpdateBaseTokenCapEvent.OutputObject
  >;
  getEvent(
    key: "UpdateBeta"
  ): TypedContractEvent<
    UpdateBetaEvent.InputTuple,
    UpdateBetaEvent.OutputTuple,
    UpdateBetaEvent.OutputObject
  >;
  getEvent(
    key: "UpdateEMASampleInterval"
  ): TypedContractEvent<
    UpdateEMASampleIntervalEvent.InputTuple,
    UpdateEMASampleIntervalEvent.OutputTuple,
    UpdateEMASampleIntervalEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePlatform"
  ): TypedContractEvent<
    UpdatePlatformEvent.InputTuple,
    UpdatePlatformEvent.OutputTuple,
    UpdatePlatformEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePriceOracle"
  ): TypedContractEvent<
    UpdatePriceOracleEvent.InputTuple,
    UpdatePriceOracleEvent.OutputTuple,
    UpdatePriceOracleEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRateProvider"
  ): TypedContractEvent<
    UpdateRateProviderEvent.InputTuple,
    UpdateRateProviderEvent.OutputTuple,
    UpdateRateProviderEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRebalancePool"
  ): TypedContractEvent<
    UpdateRebalancePoolEvent.InputTuple,
    UpdateRebalancePoolEvent.OutputTuple,
    UpdateRebalancePoolEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRewardRatio"
  ): TypedContractEvent<
    UpdateRewardRatioEvent.InputTuple,
    UpdateRewardRatioEvent.OutputTuple,
    UpdateRewardRatioEvent.OutputObject
  >;
  getEvent(
    key: "UpdateSettleWhitelist"
  ): TypedContractEvent<
    UpdateSettleWhitelistEvent.InputTuple,
    UpdateSettleWhitelistEvent.OutputTuple,
    UpdateSettleWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "V2Initialized"
  ): TypedContractEvent<
    V2InitializedEvent.InputTuple,
    V2InitializedEvent.OutputTuple,
    V2InitializedEvent.OutputObject
  >;

  filters: {
    "Harvest(address,uint256,uint256,uint256)": TypedContractEvent<
      HarvestEvent.InputTuple,
      HarvestEvent.OutputTuple,
      HarvestEvent.OutputObject
    >;
    Harvest: TypedContractEvent<
      HarvestEvent.InputTuple,
      HarvestEvent.OutputTuple,
      HarvestEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolSettle(uint256,uint256)": TypedContractEvent<
      ProtocolSettleEvent.InputTuple,
      ProtocolSettleEvent.OutputTuple,
      ProtocolSettleEvent.OutputObject
    >;
    ProtocolSettle: TypedContractEvent<
      ProtocolSettleEvent.InputTuple,
      ProtocolSettleEvent.OutputTuple,
      ProtocolSettleEvent.OutputObject
    >;

    "UpdateBaseTokenCap(uint256)": TypedContractEvent<
      UpdateBaseTokenCapEvent.InputTuple,
      UpdateBaseTokenCapEvent.OutputTuple,
      UpdateBaseTokenCapEvent.OutputObject
    >;
    UpdateBaseTokenCap: TypedContractEvent<
      UpdateBaseTokenCapEvent.InputTuple,
      UpdateBaseTokenCapEvent.OutputTuple,
      UpdateBaseTokenCapEvent.OutputObject
    >;

    "UpdateBeta(uint256)": TypedContractEvent<
      UpdateBetaEvent.InputTuple,
      UpdateBetaEvent.OutputTuple,
      UpdateBetaEvent.OutputObject
    >;
    UpdateBeta: TypedContractEvent<
      UpdateBetaEvent.InputTuple,
      UpdateBetaEvent.OutputTuple,
      UpdateBetaEvent.OutputObject
    >;

    "UpdateEMASampleInterval(uint24)": TypedContractEvent<
      UpdateEMASampleIntervalEvent.InputTuple,
      UpdateEMASampleIntervalEvent.OutputTuple,
      UpdateEMASampleIntervalEvent.OutputObject
    >;
    UpdateEMASampleInterval: TypedContractEvent<
      UpdateEMASampleIntervalEvent.InputTuple,
      UpdateEMASampleIntervalEvent.OutputTuple,
      UpdateEMASampleIntervalEvent.OutputObject
    >;

    "UpdatePlatform(address)": TypedContractEvent<
      UpdatePlatformEvent.InputTuple,
      UpdatePlatformEvent.OutputTuple,
      UpdatePlatformEvent.OutputObject
    >;
    UpdatePlatform: TypedContractEvent<
      UpdatePlatformEvent.InputTuple,
      UpdatePlatformEvent.OutputTuple,
      UpdatePlatformEvent.OutputObject
    >;

    "UpdatePriceOracle(address)": TypedContractEvent<
      UpdatePriceOracleEvent.InputTuple,
      UpdatePriceOracleEvent.OutputTuple,
      UpdatePriceOracleEvent.OutputObject
    >;
    UpdatePriceOracle: TypedContractEvent<
      UpdatePriceOracleEvent.InputTuple,
      UpdatePriceOracleEvent.OutputTuple,
      UpdatePriceOracleEvent.OutputObject
    >;

    "UpdateRateProvider(address)": TypedContractEvent<
      UpdateRateProviderEvent.InputTuple,
      UpdateRateProviderEvent.OutputTuple,
      UpdateRateProviderEvent.OutputObject
    >;
    UpdateRateProvider: TypedContractEvent<
      UpdateRateProviderEvent.InputTuple,
      UpdateRateProviderEvent.OutputTuple,
      UpdateRateProviderEvent.OutputObject
    >;

    "UpdateRebalancePool(address)": TypedContractEvent<
      UpdateRebalancePoolEvent.InputTuple,
      UpdateRebalancePoolEvent.OutputTuple,
      UpdateRebalancePoolEvent.OutputObject
    >;
    UpdateRebalancePool: TypedContractEvent<
      UpdateRebalancePoolEvent.InputTuple,
      UpdateRebalancePoolEvent.OutputTuple,
      UpdateRebalancePoolEvent.OutputObject
    >;

    "UpdateRewardRatio(uint256,uint256)": TypedContractEvent<
      UpdateRewardRatioEvent.InputTuple,
      UpdateRewardRatioEvent.OutputTuple,
      UpdateRewardRatioEvent.OutputObject
    >;
    UpdateRewardRatio: TypedContractEvent<
      UpdateRewardRatioEvent.InputTuple,
      UpdateRewardRatioEvent.OutputTuple,
      UpdateRewardRatioEvent.OutputObject
    >;

    "UpdateSettleWhitelist(address,bool)": TypedContractEvent<
      UpdateSettleWhitelistEvent.InputTuple,
      UpdateSettleWhitelistEvent.OutputTuple,
      UpdateSettleWhitelistEvent.OutputObject
    >;
    UpdateSettleWhitelist: TypedContractEvent<
      UpdateSettleWhitelistEvent.InputTuple,
      UpdateSettleWhitelistEvent.OutputTuple,
      UpdateSettleWhitelistEvent.OutputObject
    >;

    "V2Initialized(uint24)": TypedContractEvent<
      V2InitializedEvent.InputTuple,
      V2InitializedEvent.OutputTuple,
      V2InitializedEvent.OutputObject
    >;
    V2Initialized: TypedContractEvent<
      V2InitializedEvent.InputTuple,
      V2InitializedEvent.OutputTuple,
      V2InitializedEvent.OutputObject
    >;
  };
}
