/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "aToken"
      | "aTokenMintFeeRatio"
      | "aTokenMintInSystemStabilityModePaused"
      | "aTokenRedeemFeeRatio"
      | "baseToken"
      | "functionsPaused"
      | "getRoleAdmin"
      | "getRoleMember"
      | "getRoleMemberCount"
      | "grantRole"
      | "hasRole"
      | "incentiveConfig"
      | "initialize"
      | "liquidationWhitelist"
      | "marketConfig"
      | "mint"
      | "mintPaused"
      | "mintXToken"
      | "mintaToken"
      | "pauseFunctions"
      | "pauseMint"
      | "pauseRedeem"
      | "pauseXTokenRedeemInSystemStabilityMode"
      | "pauseaTokenMintInSystemStabilityMode"
      | "platform"
      | "redeem"
      | "redeemPaused"
      | "renounceRole"
      | "reservePool"
      | "revokeRole"
      | "sAVAXGateway"
      | "treasury"
      | "updateGateway"
      | "updateIncentiveConfig"
      | "updateLiquidationWhitelist"
      | "updateMarketConfig"
      | "updateMintFeeRatio"
      | "updatePlatform"
      | "updateRedeemFeeRatio"
      | "updateReservePool"
      | "xToken"
      | "xTokenMintFeeRatio"
      | "xTokenRedeemFeeRatio"
      | "xTokenRedeemInSystemStabilityModePaused"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddCollateral"
      | "Mint"
      | "PauseFunctions"
      | "PauseMint"
      | "PauseRedeem"
      | "PauseXTokenRedeemInSystemStabilityMode"
      | "PauseaTokenMintInSystemStabilityMode"
      | "Redeem"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SelfLiquidate"
      | "UpdateGateway"
      | "UpdateIncentiveConfig"
      | "UpdateLiquidationWhitelist"
      | "UpdateMarketConfig"
      | "UpdateMintFeeRatioXToken"
      | "UpdateMintFeeRatioaToken"
      | "UpdatePlatform"
      | "UpdateRedeemFeeRatioXToken"
      | "UpdateRedeemFeeRatioaToken"
      | "UpdateReservePool"
      | "UserLiquidate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aTokenMintFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aTokenMintInSystemStabilityModePaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aTokenRedeemFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "functionsPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incentiveConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintXToken",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintaToken",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseFunctions",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "pauseMint", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "pauseRedeem",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseXTokenRedeemInSystemStabilityMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseaTokenMintInSystemStabilityMode",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reservePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sAVAXGateway",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIncentiveConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidationWhitelist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMarketConfig",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMintFeeRatio",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatform",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRedeemFeeRatio",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReservePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "xToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "xTokenMintFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xTokenRedeemFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xTokenRedeemInSystemStabilityModePaused",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aTokenMintFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aTokenMintInSystemStabilityModePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aTokenRedeemFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "functionsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incentiveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidationWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintXToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseFunctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseXTokenRedeemInSystemStabilityMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseaTokenMintInSystemStabilityMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sAVAXGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIncentiveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidationWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMarketConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMintFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRedeemFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReservePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xTokenMintFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xTokenRedeemFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xTokenRedeemInSystemStabilityModePaused",
    data: BytesLike
  ): Result;
}

export namespace AddCollateralEvent {
  export type InputTuple = [
    owner: AddressLike,
    recipient: AddressLike,
    baseTokenIn: BigNumberish,
    xTokenMinted: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    recipient: string,
    baseTokenIn: bigint,
    xTokenMinted: bigint
  ];
  export interface OutputObject {
    owner: string;
    recipient: string;
    baseTokenIn: bigint;
    xTokenMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintEvent {
  export type InputTuple = [
    owner: AddressLike,
    recipient: AddressLike,
    baseTokenIn: BigNumberish,
    aTokenOut: BigNumberish,
    xTokenOut: BigNumberish,
    mintFee: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    recipient: string,
    baseTokenIn: bigint,
    aTokenOut: bigint,
    xTokenOut: bigint,
    mintFee: bigint
  ];
  export interface OutputObject {
    owner: string;
    recipient: string;
    baseTokenIn: bigint;
    aTokenOut: bigint;
    xTokenOut: bigint;
    mintFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseFunctionsEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseMintEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseRedeemEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseXTokenRedeemInSystemStabilityModeEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseaTokenMintInSystemStabilityModeEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemEvent {
  export type InputTuple = [
    owner: AddressLike,
    recipient: AddressLike,
    aTokenBurned: BigNumberish,
    xTokenBurned: BigNumberish,
    baseTokenOut: BigNumberish,
    redeemFee: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    recipient: string,
    aTokenBurned: bigint,
    xTokenBurned: bigint,
    baseTokenOut: bigint,
    redeemFee: bigint
  ];
  export interface OutputObject {
    owner: string;
    recipient: string;
    aTokenBurned: bigint;
    xTokenBurned: bigint;
    baseTokenOut: bigint;
    redeemFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SelfLiquidateEvent {
  export type InputTuple = [
    caller: AddressLike,
    baseSwapAmt: BigNumberish,
    baseTokenOut: BigNumberish,
    aTokenBurned: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    baseSwapAmt: bigint,
    baseTokenOut: bigint,
    aTokenBurned: bigint
  ];
  export interface OutputObject {
    caller: string;
    baseSwapAmt: bigint;
    baseTokenOut: bigint;
    aTokenBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateGatewayEvent {
  export type InputTuple = [gateway: AddressLike];
  export type OutputTuple = [gateway: string];
  export interface OutputObject {
    gateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateIncentiveConfigEvent {
  export type InputTuple = [
    stabilityIncentiveRatio: BigNumberish,
    liquidationIncentiveRatio: BigNumberish,
    selfLiquidationIncentiveRatio: BigNumberish
  ];
  export type OutputTuple = [
    stabilityIncentiveRatio: bigint,
    liquidationIncentiveRatio: bigint,
    selfLiquidationIncentiveRatio: bigint
  ];
  export interface OutputObject {
    stabilityIncentiveRatio: bigint;
    liquidationIncentiveRatio: bigint;
    selfLiquidationIncentiveRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateLiquidationWhitelistEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateMarketConfigEvent {
  export type InputTuple = [
    stabilityRatio: BigNumberish,
    liquidationRatio: BigNumberish,
    selfLiquidationRatio: BigNumberish,
    recapRatio: BigNumberish
  ];
  export type OutputTuple = [
    stabilityRatio: bigint,
    liquidationRatio: bigint,
    selfLiquidationRatio: bigint,
    recapRatio: bigint
  ];
  export interface OutputObject {
    stabilityRatio: bigint;
    liquidationRatio: bigint;
    selfLiquidationRatio: bigint;
    recapRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateMintFeeRatioXTokenEvent {
  export type InputTuple = [
    defaultFeeRatio: BigNumberish,
    extraFeeRatio: BigNumberish
  ];
  export type OutputTuple = [defaultFeeRatio: bigint, extraFeeRatio: bigint];
  export interface OutputObject {
    defaultFeeRatio: bigint;
    extraFeeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateMintFeeRatioaTokenEvent {
  export type InputTuple = [
    defaultFeeRatio: BigNumberish,
    extraFeeRatio: BigNumberish
  ];
  export type OutputTuple = [defaultFeeRatio: bigint, extraFeeRatio: bigint];
  export interface OutputObject {
    defaultFeeRatio: bigint;
    extraFeeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePlatformEvent {
  export type InputTuple = [platform: AddressLike];
  export type OutputTuple = [platform: string];
  export interface OutputObject {
    platform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRedeemFeeRatioXTokenEvent {
  export type InputTuple = [
    defaultFeeRatio: BigNumberish,
    extraFeeRatio: BigNumberish
  ];
  export type OutputTuple = [defaultFeeRatio: bigint, extraFeeRatio: bigint];
  export interface OutputObject {
    defaultFeeRatio: bigint;
    extraFeeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRedeemFeeRatioaTokenEvent {
  export type InputTuple = [
    defaultFeeRatio: BigNumberish,
    extraFeeRatio: BigNumberish
  ];
  export type OutputTuple = [defaultFeeRatio: bigint, extraFeeRatio: bigint];
  export interface OutputObject {
    defaultFeeRatio: bigint;
    extraFeeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateReservePoolEvent {
  export type InputTuple = [reservePool: AddressLike];
  export type OutputTuple = [reservePool: string];
  export interface OutputObject {
    reservePool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserLiquidateEvent {
  export type InputTuple = [
    owner: AddressLike,
    recipient: AddressLike,
    aTokenBurned: BigNumberish,
    baseTokenOut: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    recipient: string,
    aTokenBurned: bigint,
    baseTokenOut: bigint
  ];
  export interface OutputObject {
    owner: string;
    recipient: string;
    aTokenBurned: bigint;
    baseTokenOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Market extends BaseContract {
  connect(runner?: ContractRunner | null): Market;
  waitForDeployment(): Promise<this>;

  interface: MarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  aToken: TypedContractMethod<[], [string], "view">;

  aTokenMintFeeRatio: TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;

  aTokenMintInSystemStabilityModePaused: TypedContractMethod<
    [],
    [boolean],
    "view"
  >;

  aTokenRedeemFeeRatio: TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;

  baseToken: TypedContractMethod<[], [string], "view">;

  functionsPaused: TypedContractMethod<[], [boolean], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoleMember: TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;

  getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  incentiveConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        stabilityIncentiveRatio: bigint;
        liquidationIncentiveRatio: bigint;
        selfLiquidationIncentiveRatio: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [_treasury: AddressLike, _platform: AddressLike, _gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  liquidationWhitelist: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  marketConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        stabilityRatio: bigint;
        liquidationRatio: bigint;
        selfLiquidationRatio: bigint;
        recapRatio: bigint;
      }
    ],
    "view"
  >;

  mint: TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minaTokenMinted: BigNumberish,
      _minXTokenMinted: BigNumberish
    ],
    [[bigint, bigint] & { _aTokenMinted: bigint; _xTokenMinted: bigint }],
    "nonpayable"
  >;

  mintPaused: TypedContractMethod<[], [boolean], "view">;

  mintXToken: TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minXTokenMinted: BigNumberish
    ],
    [[bigint, bigint] & { _xTokenMinted: bigint; _bonus: bigint }],
    "nonpayable"
  >;

  mintaToken: TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minaTokenMinted: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  pauseFunctions: TypedContractMethod<[_status: boolean], [void], "nonpayable">;

  pauseMint: TypedContractMethod<[_status: boolean], [void], "nonpayable">;

  pauseRedeem: TypedContractMethod<[_status: boolean], [void], "nonpayable">;

  pauseXTokenRedeemInSystemStabilityMode: TypedContractMethod<
    [_status: boolean],
    [void],
    "nonpayable"
  >;

  pauseaTokenMintInSystemStabilityMode: TypedContractMethod<
    [_status: boolean],
    [void],
    "nonpayable"
  >;

  platform: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<
    [
      _aTokenIn: BigNumberish,
      _xTokenIn: BigNumberish,
      _recipient: AddressLike,
      _minBaseOut: BigNumberish
    ],
    [[bigint, bigint] & { _baseOut: bigint; _bonus: bigint }],
    "nonpayable"
  >;

  redeemPaused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  reservePool: TypedContractMethod<[], [string], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sAVAXGateway: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  updateGateway: TypedContractMethod<
    [_gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  updateIncentiveConfig: TypedContractMethod<
    [
      _stabilityIncentiveRatio: BigNumberish,
      _liquidationIncentiveRatio: BigNumberish,
      _selfLiquidationIncentiveRatio: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateLiquidationWhitelist: TypedContractMethod<
    [_account: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  updateMarketConfig: TypedContractMethod<
    [
      _stabilityRatio: BigNumberish,
      _liquidationRatio: BigNumberish,
      _selfLiquidationRatio: BigNumberish,
      _recapRatio: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateMintFeeRatio: TypedContractMethod<
    [
      _defaultFeeRatio: BigNumberish,
      _extraFeeRatio: BigNumberish,
      _isaToken: boolean
    ],
    [void],
    "nonpayable"
  >;

  updatePlatform: TypedContractMethod<
    [_platform: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRedeemFeeRatio: TypedContractMethod<
    [
      _defaultFeeRatio: BigNumberish,
      _extraFeeRatio: BigNumberish,
      _isaToken: boolean
    ],
    [void],
    "nonpayable"
  >;

  updateReservePool: TypedContractMethod<
    [_reservePool: AddressLike],
    [void],
    "nonpayable"
  >;

  xToken: TypedContractMethod<[], [string], "view">;

  xTokenMintFeeRatio: TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;

  xTokenRedeemFeeRatio: TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;

  xTokenRedeemInSystemStabilityModePaused: TypedContractMethod<
    [],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aTokenMintFeeRatio"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "aTokenMintInSystemStabilityModePaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "aTokenRedeemFeeRatio"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "functionsPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleMember"
  ): TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleMemberCount"
  ): TypedContractMethod<[role: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "incentiveConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        stabilityIncentiveRatio: bigint;
        liquidationIncentiveRatio: bigint;
        selfLiquidationIncentiveRatio: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_treasury: AddressLike, _platform: AddressLike, _gateway: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidationWhitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        stabilityRatio: bigint;
        liquidationRatio: bigint;
        selfLiquidationRatio: bigint;
        recapRatio: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minaTokenMinted: BigNumberish,
      _minXTokenMinted: BigNumberish
    ],
    [[bigint, bigint] & { _aTokenMinted: bigint; _xTokenMinted: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintXToken"
  ): TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minXTokenMinted: BigNumberish
    ],
    [[bigint, bigint] & { _xTokenMinted: bigint; _bonus: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintaToken"
  ): TypedContractMethod<
    [
      _baseIn: BigNumberish,
      _recipient: AddressLike,
      _minaTokenMinted: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pauseFunctions"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseMint"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseRedeem"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseXTokenRedeemInSystemStabilityMode"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseaTokenMintInSystemStabilityMode"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "platform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [
      _aTokenIn: BigNumberish,
      _xTokenIn: BigNumberish,
      _recipient: AddressLike,
      _minBaseOut: BigNumberish
    ],
    [[bigint, bigint] & { _baseOut: bigint; _bonus: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sAVAXGateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateGateway"
  ): TypedContractMethod<[_gateway: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateIncentiveConfig"
  ): TypedContractMethod<
    [
      _stabilityIncentiveRatio: BigNumberish,
      _liquidationIncentiveRatio: BigNumberish,
      _selfLiquidationIncentiveRatio: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLiquidationWhitelist"
  ): TypedContractMethod<
    [_account: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMarketConfig"
  ): TypedContractMethod<
    [
      _stabilityRatio: BigNumberish,
      _liquidationRatio: BigNumberish,
      _selfLiquidationRatio: BigNumberish,
      _recapRatio: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMintFeeRatio"
  ): TypedContractMethod<
    [
      _defaultFeeRatio: BigNumberish,
      _extraFeeRatio: BigNumberish,
      _isaToken: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlatform"
  ): TypedContractMethod<[_platform: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRedeemFeeRatio"
  ): TypedContractMethod<
    [
      _defaultFeeRatio: BigNumberish,
      _extraFeeRatio: BigNumberish,
      _isaToken: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReservePool"
  ): TypedContractMethod<[_reservePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "xTokenMintFeeRatio"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "xTokenRedeemFeeRatio"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { defaultFeeRatio: bigint; extraFeeRatio: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "xTokenRedeemInSystemStabilityModePaused"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "AddCollateral"
  ): TypedContractEvent<
    AddCollateralEvent.InputTuple,
    AddCollateralEvent.OutputTuple,
    AddCollateralEvent.OutputObject
  >;
  getEvent(
    key: "Mint"
  ): TypedContractEvent<
    MintEvent.InputTuple,
    MintEvent.OutputTuple,
    MintEvent.OutputObject
  >;
  getEvent(
    key: "PauseFunctions"
  ): TypedContractEvent<
    PauseFunctionsEvent.InputTuple,
    PauseFunctionsEvent.OutputTuple,
    PauseFunctionsEvent.OutputObject
  >;
  getEvent(
    key: "PauseMint"
  ): TypedContractEvent<
    PauseMintEvent.InputTuple,
    PauseMintEvent.OutputTuple,
    PauseMintEvent.OutputObject
  >;
  getEvent(
    key: "PauseRedeem"
  ): TypedContractEvent<
    PauseRedeemEvent.InputTuple,
    PauseRedeemEvent.OutputTuple,
    PauseRedeemEvent.OutputObject
  >;
  getEvent(
    key: "PauseXTokenRedeemInSystemStabilityMode"
  ): TypedContractEvent<
    PauseXTokenRedeemInSystemStabilityModeEvent.InputTuple,
    PauseXTokenRedeemInSystemStabilityModeEvent.OutputTuple,
    PauseXTokenRedeemInSystemStabilityModeEvent.OutputObject
  >;
  getEvent(
    key: "PauseaTokenMintInSystemStabilityMode"
  ): TypedContractEvent<
    PauseaTokenMintInSystemStabilityModeEvent.InputTuple,
    PauseaTokenMintInSystemStabilityModeEvent.OutputTuple,
    PauseaTokenMintInSystemStabilityModeEvent.OutputObject
  >;
  getEvent(
    key: "Redeem"
  ): TypedContractEvent<
    RedeemEvent.InputTuple,
    RedeemEvent.OutputTuple,
    RedeemEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SelfLiquidate"
  ): TypedContractEvent<
    SelfLiquidateEvent.InputTuple,
    SelfLiquidateEvent.OutputTuple,
    SelfLiquidateEvent.OutputObject
  >;
  getEvent(
    key: "UpdateGateway"
  ): TypedContractEvent<
    UpdateGatewayEvent.InputTuple,
    UpdateGatewayEvent.OutputTuple,
    UpdateGatewayEvent.OutputObject
  >;
  getEvent(
    key: "UpdateIncentiveConfig"
  ): TypedContractEvent<
    UpdateIncentiveConfigEvent.InputTuple,
    UpdateIncentiveConfigEvent.OutputTuple,
    UpdateIncentiveConfigEvent.OutputObject
  >;
  getEvent(
    key: "UpdateLiquidationWhitelist"
  ): TypedContractEvent<
    UpdateLiquidationWhitelistEvent.InputTuple,
    UpdateLiquidationWhitelistEvent.OutputTuple,
    UpdateLiquidationWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "UpdateMarketConfig"
  ): TypedContractEvent<
    UpdateMarketConfigEvent.InputTuple,
    UpdateMarketConfigEvent.OutputTuple,
    UpdateMarketConfigEvent.OutputObject
  >;
  getEvent(
    key: "UpdateMintFeeRatioXToken"
  ): TypedContractEvent<
    UpdateMintFeeRatioXTokenEvent.InputTuple,
    UpdateMintFeeRatioXTokenEvent.OutputTuple,
    UpdateMintFeeRatioXTokenEvent.OutputObject
  >;
  getEvent(
    key: "UpdateMintFeeRatioaToken"
  ): TypedContractEvent<
    UpdateMintFeeRatioaTokenEvent.InputTuple,
    UpdateMintFeeRatioaTokenEvent.OutputTuple,
    UpdateMintFeeRatioaTokenEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePlatform"
  ): TypedContractEvent<
    UpdatePlatformEvent.InputTuple,
    UpdatePlatformEvent.OutputTuple,
    UpdatePlatformEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRedeemFeeRatioXToken"
  ): TypedContractEvent<
    UpdateRedeemFeeRatioXTokenEvent.InputTuple,
    UpdateRedeemFeeRatioXTokenEvent.OutputTuple,
    UpdateRedeemFeeRatioXTokenEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRedeemFeeRatioaToken"
  ): TypedContractEvent<
    UpdateRedeemFeeRatioaTokenEvent.InputTuple,
    UpdateRedeemFeeRatioaTokenEvent.OutputTuple,
    UpdateRedeemFeeRatioaTokenEvent.OutputObject
  >;
  getEvent(
    key: "UpdateReservePool"
  ): TypedContractEvent<
    UpdateReservePoolEvent.InputTuple,
    UpdateReservePoolEvent.OutputTuple,
    UpdateReservePoolEvent.OutputObject
  >;
  getEvent(
    key: "UserLiquidate"
  ): TypedContractEvent<
    UserLiquidateEvent.InputTuple,
    UserLiquidateEvent.OutputTuple,
    UserLiquidateEvent.OutputObject
  >;

  filters: {
    "AddCollateral(address,address,uint256,uint256)": TypedContractEvent<
      AddCollateralEvent.InputTuple,
      AddCollateralEvent.OutputTuple,
      AddCollateralEvent.OutputObject
    >;
    AddCollateral: TypedContractEvent<
      AddCollateralEvent.InputTuple,
      AddCollateralEvent.OutputTuple,
      AddCollateralEvent.OutputObject
    >;

    "Mint(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;
    Mint: TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;

    "PauseFunctions(bool)": TypedContractEvent<
      PauseFunctionsEvent.InputTuple,
      PauseFunctionsEvent.OutputTuple,
      PauseFunctionsEvent.OutputObject
    >;
    PauseFunctions: TypedContractEvent<
      PauseFunctionsEvent.InputTuple,
      PauseFunctionsEvent.OutputTuple,
      PauseFunctionsEvent.OutputObject
    >;

    "PauseMint(bool)": TypedContractEvent<
      PauseMintEvent.InputTuple,
      PauseMintEvent.OutputTuple,
      PauseMintEvent.OutputObject
    >;
    PauseMint: TypedContractEvent<
      PauseMintEvent.InputTuple,
      PauseMintEvent.OutputTuple,
      PauseMintEvent.OutputObject
    >;

    "PauseRedeem(bool)": TypedContractEvent<
      PauseRedeemEvent.InputTuple,
      PauseRedeemEvent.OutputTuple,
      PauseRedeemEvent.OutputObject
    >;
    PauseRedeem: TypedContractEvent<
      PauseRedeemEvent.InputTuple,
      PauseRedeemEvent.OutputTuple,
      PauseRedeemEvent.OutputObject
    >;

    "PauseXTokenRedeemInSystemStabilityMode(bool)": TypedContractEvent<
      PauseXTokenRedeemInSystemStabilityModeEvent.InputTuple,
      PauseXTokenRedeemInSystemStabilityModeEvent.OutputTuple,
      PauseXTokenRedeemInSystemStabilityModeEvent.OutputObject
    >;
    PauseXTokenRedeemInSystemStabilityMode: TypedContractEvent<
      PauseXTokenRedeemInSystemStabilityModeEvent.InputTuple,
      PauseXTokenRedeemInSystemStabilityModeEvent.OutputTuple,
      PauseXTokenRedeemInSystemStabilityModeEvent.OutputObject
    >;

    "PauseaTokenMintInSystemStabilityMode(bool)": TypedContractEvent<
      PauseaTokenMintInSystemStabilityModeEvent.InputTuple,
      PauseaTokenMintInSystemStabilityModeEvent.OutputTuple,
      PauseaTokenMintInSystemStabilityModeEvent.OutputObject
    >;
    PauseaTokenMintInSystemStabilityMode: TypedContractEvent<
      PauseaTokenMintInSystemStabilityModeEvent.InputTuple,
      PauseaTokenMintInSystemStabilityModeEvent.OutputTuple,
      PauseaTokenMintInSystemStabilityModeEvent.OutputObject
    >;

    "Redeem(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RedeemEvent.InputTuple,
      RedeemEvent.OutputTuple,
      RedeemEvent.OutputObject
    >;
    Redeem: TypedContractEvent<
      RedeemEvent.InputTuple,
      RedeemEvent.OutputTuple,
      RedeemEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SelfLiquidate(address,uint256,uint256,uint256)": TypedContractEvent<
      SelfLiquidateEvent.InputTuple,
      SelfLiquidateEvent.OutputTuple,
      SelfLiquidateEvent.OutputObject
    >;
    SelfLiquidate: TypedContractEvent<
      SelfLiquidateEvent.InputTuple,
      SelfLiquidateEvent.OutputTuple,
      SelfLiquidateEvent.OutputObject
    >;

    "UpdateGateway(address)": TypedContractEvent<
      UpdateGatewayEvent.InputTuple,
      UpdateGatewayEvent.OutputTuple,
      UpdateGatewayEvent.OutputObject
    >;
    UpdateGateway: TypedContractEvent<
      UpdateGatewayEvent.InputTuple,
      UpdateGatewayEvent.OutputTuple,
      UpdateGatewayEvent.OutputObject
    >;

    "UpdateIncentiveConfig(uint64,uint64,uint64)": TypedContractEvent<
      UpdateIncentiveConfigEvent.InputTuple,
      UpdateIncentiveConfigEvent.OutputTuple,
      UpdateIncentiveConfigEvent.OutputObject
    >;
    UpdateIncentiveConfig: TypedContractEvent<
      UpdateIncentiveConfigEvent.InputTuple,
      UpdateIncentiveConfigEvent.OutputTuple,
      UpdateIncentiveConfigEvent.OutputObject
    >;

    "UpdateLiquidationWhitelist(address,bool)": TypedContractEvent<
      UpdateLiquidationWhitelistEvent.InputTuple,
      UpdateLiquidationWhitelistEvent.OutputTuple,
      UpdateLiquidationWhitelistEvent.OutputObject
    >;
    UpdateLiquidationWhitelist: TypedContractEvent<
      UpdateLiquidationWhitelistEvent.InputTuple,
      UpdateLiquidationWhitelistEvent.OutputTuple,
      UpdateLiquidationWhitelistEvent.OutputObject
    >;

    "UpdateMarketConfig(uint64,uint64,uint64,uint64)": TypedContractEvent<
      UpdateMarketConfigEvent.InputTuple,
      UpdateMarketConfigEvent.OutputTuple,
      UpdateMarketConfigEvent.OutputObject
    >;
    UpdateMarketConfig: TypedContractEvent<
      UpdateMarketConfigEvent.InputTuple,
      UpdateMarketConfigEvent.OutputTuple,
      UpdateMarketConfigEvent.OutputObject
    >;

    "UpdateMintFeeRatioXToken(uint128,int128)": TypedContractEvent<
      UpdateMintFeeRatioXTokenEvent.InputTuple,
      UpdateMintFeeRatioXTokenEvent.OutputTuple,
      UpdateMintFeeRatioXTokenEvent.OutputObject
    >;
    UpdateMintFeeRatioXToken: TypedContractEvent<
      UpdateMintFeeRatioXTokenEvent.InputTuple,
      UpdateMintFeeRatioXTokenEvent.OutputTuple,
      UpdateMintFeeRatioXTokenEvent.OutputObject
    >;

    "UpdateMintFeeRatioaToken(uint128,int128)": TypedContractEvent<
      UpdateMintFeeRatioaTokenEvent.InputTuple,
      UpdateMintFeeRatioaTokenEvent.OutputTuple,
      UpdateMintFeeRatioaTokenEvent.OutputObject
    >;
    UpdateMintFeeRatioaToken: TypedContractEvent<
      UpdateMintFeeRatioaTokenEvent.InputTuple,
      UpdateMintFeeRatioaTokenEvent.OutputTuple,
      UpdateMintFeeRatioaTokenEvent.OutputObject
    >;

    "UpdatePlatform(address)": TypedContractEvent<
      UpdatePlatformEvent.InputTuple,
      UpdatePlatformEvent.OutputTuple,
      UpdatePlatformEvent.OutputObject
    >;
    UpdatePlatform: TypedContractEvent<
      UpdatePlatformEvent.InputTuple,
      UpdatePlatformEvent.OutputTuple,
      UpdatePlatformEvent.OutputObject
    >;

    "UpdateRedeemFeeRatioXToken(uint128,int128)": TypedContractEvent<
      UpdateRedeemFeeRatioXTokenEvent.InputTuple,
      UpdateRedeemFeeRatioXTokenEvent.OutputTuple,
      UpdateRedeemFeeRatioXTokenEvent.OutputObject
    >;
    UpdateRedeemFeeRatioXToken: TypedContractEvent<
      UpdateRedeemFeeRatioXTokenEvent.InputTuple,
      UpdateRedeemFeeRatioXTokenEvent.OutputTuple,
      UpdateRedeemFeeRatioXTokenEvent.OutputObject
    >;

    "UpdateRedeemFeeRatioaToken(uint128,int128)": TypedContractEvent<
      UpdateRedeemFeeRatioaTokenEvent.InputTuple,
      UpdateRedeemFeeRatioaTokenEvent.OutputTuple,
      UpdateRedeemFeeRatioaTokenEvent.OutputObject
    >;
    UpdateRedeemFeeRatioaToken: TypedContractEvent<
      UpdateRedeemFeeRatioaTokenEvent.InputTuple,
      UpdateRedeemFeeRatioaTokenEvent.OutputTuple,
      UpdateRedeemFeeRatioaTokenEvent.OutputObject
    >;

    "UpdateReservePool(address)": TypedContractEvent<
      UpdateReservePoolEvent.InputTuple,
      UpdateReservePoolEvent.OutputTuple,
      UpdateReservePoolEvent.OutputObject
    >;
    UpdateReservePool: TypedContractEvent<
      UpdateReservePoolEvent.InputTuple,
      UpdateReservePoolEvent.OutputTuple,
      UpdateReservePoolEvent.OutputObject
    >;

    "UserLiquidate(address,address,uint256,uint256)": TypedContractEvent<
      UserLiquidateEvent.InputTuple,
      UserLiquidateEvent.OutputTuple,
      UserLiquidateEvent.OutputObject
    >;
    UserLiquidate: TypedContractEvent<
      UserLiquidateEvent.InputTuple,
      UserLiquidateEvent.OutputTuple,
      UserLiquidateEvent.OutputObject
    >;
  };
}
