/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackTreasury,
  IJackTreasuryInterface,
} from "../../../interfaces/jack/IJackTreasury";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "aNav",
        type: "uint256",
      },
    ],
    name: "ProtocolSettle",
    type: "event",
  },
  {
    inputs: [],
    name: "aToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "collateralRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "convertToUnwrapped",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "convertToWrapped",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentBaseTokenPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentNav",
    outputs: [
      {
        internalType: "uint256",
        name: "baseNav",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "aNav",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xNav",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isBaseTokenPriceValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isUnderCollateral",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastPermissionedPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "leverageRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "incentiveRatio",
        type: "uint256",
      },
    ],
    name: "maxLiquidatable",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxaTokenLiquidatable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
    ],
    name: "maxMintableXToken",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxXTokenMintable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "incentiveRatio",
        type: "uint256",
      },
    ],
    name: "maxMintableXTokenWithIncentive",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxXTokenMintable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
    ],
    name: "maxMintableaToken",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxaTokenMintable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
    ],
    name: "maxRedeemableXToken",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxXTokenRedeemable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newCollateralRatio",
        type: "uint256",
      },
    ],
    name: "maxRedeemableaToken",
    outputs: [
      {
        internalType: "uint256",
        name: "maxBaseOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxaTokenRedeemable",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "baseIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "enum IJackTreasury.MintOption",
        name: "option",
        type: "uint8",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "aTokenOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xTokenOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "aTokenIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xTokenIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "redeem",
    outputs: [
      {
        internalType: "uint256",
        name: "baseOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBaseToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "xAVAXLeverageRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "xToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJackTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IJackTreasuryInterface {
    return new Interface(_abi) as IJackTreasuryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJackTreasury {
    return new Contract(address, _abi, runner) as unknown as IJackTreasury;
  }
}
