/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackLeveragedToken,
  IJackLeveragedTokenInterface,
} from "../../../interfaces/jack/IJackLeveragedToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nav",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJackLeveragedToken__factory {
  static readonly abi = _abi;
  static createInterface(): IJackLeveragedTokenInterface {
    return new Interface(_abi) as IJackLeveragedTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJackLeveragedToken {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IJackLeveragedToken;
  }
}
