/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackReservePool,
  IJackReservePoolInterface,
} from "../../../interfaces/jack/IJackReservePool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "originalAmount",
        type: "uint256",
      },
    ],
    name: "requestBonus",
    outputs: [
      {
        internalType: "uint256",
        name: "bonus",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJackReservePool__factory {
  static readonly abi = _abi;
  static createInterface(): IJackReservePoolInterface {
    return new Interface(_abi) as IJackReservePoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJackReservePool {
    return new Contract(address, _abi, runner) as unknown as IJackReservePool;
  }
}
