/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackPriceOracle,
  IJackPriceOracleInterface,
} from "../../../interfaces/jack/IJackPriceOracle";

const _abi = [
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "safePrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJackPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IJackPriceOracleInterface {
    return new Interface(_abi) as IJackPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJackPriceOracle {
    return new Contract(address, _abi, runner) as unknown as IJackPriceOracle;
  }
}
