/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackSyntheticToken,
  IJackSyntheticTokenInterface,
} from "../../../interfaces/jack/IJackSyntheticToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nav",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJackSyntheticToken__factory {
  static readonly abi = _abi;
  static createInterface(): IJackSyntheticTokenInterface {
    return new Interface(_abi) as IJackSyntheticTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJackSyntheticToken {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IJackSyntheticToken;
  }
}
