/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RebalancePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReward"
      | "asset"
      | "balanceOf"
      | "baseRewardToken"
      | "baseToken"
      | "claim(address[],bool)"
      | "claim(address,bool)"
      | "claimable"
      | "deposit"
      | "depositReward"
      | "epochState"
      | "epochToScaleToBaseRewardSum"
      | "epochToScaleToExtraRewardSum"
      | "extraRewardState"
      | "extraRewards"
      | "extraRewardsLength"
      | "initialize"
      | "lastAssetLossError"
      | "liquidatableCollateralRatio"
      | "liquidate"
      | "liquidator"
      | "market"
      | "owner"
      | "removeReward"
      | "renounceOwnership"
      | "rewardManager"
      | "totalSupply"
      | "totalUnlocking"
      | "transferOwnership"
      | "treasury"
      | "unlock"
      | "unlockDuration"
      | "unlockedBalanceOf"
      | "unlockingBalanceOf"
      | "updateAccountSnapshot"
      | "updateLiquidatableCollateralRatio"
      | "updateLiquidator"
      | "updateReward"
      | "updateUnlockDuration"
      | "withdrawUnlocked"
      | "wrapper"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountSnapshotTaken"
      | "AddRewardToken"
      | "Claim"
      | "Deposit"
      | "DepositReward"
      | "Liquidate"
      | "LossNotified"
      | "OwnershipTransferred"
      | "RemoveRewardToken"
      | "RewardsAccumulated"
      | "RewardsDistributed"
      | "Unlock"
      | "UpdateLiquidatableCollateralRatio"
      | "UpdateLiquidator"
      | "UpdateRewardToken"
      | "UpdateUnlockDuration"
      | "UpdateWrapper"
      | "UserDepositChange"
      | "UserUnlockChange"
      | "WithdrawUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReward",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "baseRewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claim(address[],bool)",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claim(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochToScaleToBaseRewardSum",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochToScaleToExtraRewardSum",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extraRewardState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extraRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extraRewardsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAssetLossError",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatableCollateralRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUnlocking",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockedBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockingBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAccountSnapshot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidatableCollateralRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReward",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUnlockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnlocked",
    values: [boolean, boolean]
  ): string;
  encodeFunctionData(functionFragment: "wrapper", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claim(address[],bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claim(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochToScaleToBaseRewardSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochToScaleToExtraRewardSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraRewardState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraRewardsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastAssetLossError",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatableCollateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUnlocking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockedBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockingBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAccountSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidatableCollateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUnlockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrapper", data: BytesLike): Result;
}

export namespace AccountSnapshotTakenEvent {
  export type InputTuple = [
    account: AddressLike,
    newDeposit: BigNumberish,
    newUnlock: BigNumberish,
    epoch: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    newDeposit: bigint,
    newUnlock: bigint,
    epoch: bigint
  ];
  export interface OutputObject {
    account: string;
    newDeposit: bigint;
    newUnlock: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddRewardTokenEvent {
  export type InputTuple = [
    token: AddressLike,
    manager: AddressLike,
    periodLength: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    manager: string,
    periodLength: bigint
  ];
  export interface OutputObject {
    token: string;
    manager: string;
    periodLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimEvent {
  export type InputTuple = [
    owner: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [owner: string, token: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    owner: AddressLike,
    reciever: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [owner: string, reciever: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    reciever: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRewardEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidateEvent {
  export type InputTuple = [liquidated: BigNumberish, baseGained: BigNumberish];
  export type OutputTuple = [liquidated: bigint, baseGained: bigint];
  export interface OutputObject {
    liquidated: bigint;
    baseGained: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LossNotifiedEvent {
  export type InputTuple = [
    loss: BigNumberish,
    baseOut: BigNumberish,
    assetLossPerUnitStaked: BigNumberish,
    epoch: BigNumberish,
    scale: BigNumberish,
    newProductFactor: BigNumberish
  ];
  export type OutputTuple = [
    loss: bigint,
    baseOut: bigint,
    assetLossPerUnitStaked: bigint,
    epoch: bigint,
    scale: bigint,
    newProductFactor: bigint
  ];
  export interface OutputObject {
    loss: bigint;
    baseOut: bigint;
    assetLossPerUnitStaked: bigint;
    epoch: bigint;
    scale: bigint;
    newProductFactor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveRewardTokenEvent {
  export type InputTuple = [index: BigNumberish, token: AddressLike];
  export type OutputTuple = [index: bigint, token: string];
  export interface OutputObject {
    index: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsAccumulatedEvent {
  export type InputTuple = [
    token: AddressLike,
    pending: BigNumberish,
    rewardsPerUnitStaked: BigNumberish,
    epoch: BigNumberish,
    scale: BigNumberish,
    newRewardSum: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    pending: bigint,
    rewardsPerUnitStaked: bigint,
    epoch: bigint,
    scale: bigint,
    newRewardSum: bigint
  ];
  export interface OutputObject {
    token: string;
    pending: bigint;
    rewardsPerUnitStaked: bigint;
    epoch: bigint;
    scale: bigint;
    newRewardSum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    token: AddressLike,
    duration: BigNumberish,
    pending: BigNumberish,
    accumulated: boolean
  ];
  export type OutputTuple = [
    token: string,
    duration: bigint,
    pending: bigint,
    accumulated: boolean
  ];
  export interface OutputObject {
    token: string;
    duration: bigint;
    pending: bigint;
    accumulated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockEvent {
  export type InputTuple = [
    owner: AddressLike,
    amount: BigNumberish,
    unlockAt: BigNumberish
  ];
  export type OutputTuple = [owner: string, amount: bigint, unlockAt: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
    unlockAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateLiquidatableCollateralRatioEvent {
  export type InputTuple = [liquidatableCollateralRatio: BigNumberish];
  export type OutputTuple = [liquidatableCollateralRatio: bigint];
  export interface OutputObject {
    liquidatableCollateralRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateLiquidatorEvent {
  export type InputTuple = [liquidator: AddressLike];
  export type OutputTuple = [liquidator: string];
  export interface OutputObject {
    liquidator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRewardTokenEvent {
  export type InputTuple = [
    token: AddressLike,
    manager: AddressLike,
    periodLength: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    manager: string,
    periodLength: bigint
  ];
  export interface OutputObject {
    token: string;
    manager: string;
    periodLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateUnlockDurationEvent {
  export type InputTuple = [unlockDuration: BigNumberish];
  export type OutputTuple = [unlockDuration: bigint];
  export interface OutputObject {
    unlockDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateWrapperEvent {
  export type InputTuple = [wrapper: AddressLike];
  export type OutputTuple = [wrapper: string];
  export interface OutputObject {
    wrapper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDepositChangeEvent {
  export type InputTuple = [
    owner: AddressLike,
    newDeposit: BigNumberish,
    loss: BigNumberish
  ];
  export type OutputTuple = [owner: string, newDeposit: bigint, loss: bigint];
  export interface OutputObject {
    owner: string;
    newDeposit: bigint;
    loss: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserUnlockChangeEvent {
  export type InputTuple = [
    owner: AddressLike,
    newUnlock: BigNumberish,
    loss: BigNumberish
  ];
  export type OutputTuple = [owner: string, newUnlock: bigint, loss: bigint];
  export interface OutputObject {
    owner: string;
    newUnlock: bigint;
    loss: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawUnlockedEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RebalancePool extends BaseContract {
  connect(runner?: ContractRunner | null): RebalancePool;
  waitForDeployment(): Promise<this>;

  interface: RebalancePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReward: TypedContractMethod<
    [_token: AddressLike, _manager: AddressLike, _periodLength: BigNumberish],
    [void],
    "nonpayable"
  >;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[_account: AddressLike], [bigint], "view">;

  baseRewardToken: TypedContractMethod<[], [string], "view">;

  baseToken: TypedContractMethod<[], [string], "view">;

  "claim(address[],bool)": TypedContractMethod<
    [_tokens: AddressLike[], _unwrap: boolean],
    [void],
    "nonpayable"
  >;

  "claim(address,bool)": TypedContractMethod<
    [_token: AddressLike, _unwrap: boolean],
    [void],
    "nonpayable"
  >;

  claimable: TypedContractMethod<
    [_account: AddressLike, _token: AddressLike],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<
    [_amount: BigNumberish, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  depositReward: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  epochState: TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { epoch: bigint; scale: bigint; prod: bigint }],
    "view"
  >;

  epochToScaleToBaseRewardSum: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  epochToScaleToExtraRewardSum: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  extraRewardState: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        rate: bigint;
        periodLength: bigint;
        lastUpdate: bigint;
        finishAt: bigint;
        queued: bigint;
      }
    ],
    "view"
  >;

  extraRewards: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  extraRewardsLength: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [_treasury: AddressLike, _market: AddressLike],
    [void],
    "nonpayable"
  >;

  lastAssetLossError: TypedContractMethod<[], [bigint], "view">;

  liquidatableCollateralRatio: TypedContractMethod<[], [bigint], "view">;

  liquidate: TypedContractMethod<
    [_maxAmount: BigNumberish, _minBaseOut: BigNumberish],
    [[bigint, bigint] & { _liquidated: bigint; _baseOut: bigint }],
    "nonpayable"
  >;

  liquidator: TypedContractMethod<[], [string], "view">;

  market: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeReward: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardManager: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalUnlocking: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unlock: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  unlockDuration: TypedContractMethod<[], [bigint], "view">;

  unlockedBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  unlockingBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { _balance: bigint; _unlockAt: bigint }],
    "view"
  >;

  updateAccountSnapshot: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLiquidatableCollateralRatio: TypedContractMethod<
    [_liquidatableCollateralRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateLiquidator: TypedContractMethod<
    [_liquidator: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReward: TypedContractMethod<
    [_token: AddressLike, _manager: AddressLike, _periodLength: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateUnlockDuration: TypedContractMethod<
    [_unlockDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawUnlocked: TypedContractMethod<
    [_doClaim: boolean, _unwrap: boolean],
    [void],
    "nonpayable"
  >;

  wrapper: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReward"
  ): TypedContractMethod<
    [_token: AddressLike, _manager: AddressLike, _periodLength: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseRewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim(address[],bool)"
  ): TypedContractMethod<
    [_tokens: AddressLike[], _unwrap: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim(address,bool)"
  ): TypedContractMethod<
    [_token: AddressLike, _unwrap: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<
    [_account: AddressLike, _token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [_amount: BigNumberish, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositReward"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochState"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { epoch: bigint; scale: bigint; prod: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochToScaleToBaseRewardSum"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochToScaleToExtraRewardSum"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "extraRewardState"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        rate: bigint;
        periodLength: bigint;
        lastUpdate: bigint;
        finishAt: bigint;
        queued: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "extraRewards"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "extraRewardsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_treasury: AddressLike, _market: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastAssetLossError"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidatableCollateralRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [_maxAmount: BigNumberish, _minBaseOut: BigNumberish],
    [[bigint, bigint] & { _liquidated: bigint; _baseOut: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "market"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeReward"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardManager"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUnlocking"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlock"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockedBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockingBalanceOf"
  ): TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { _balance: bigint; _unlockAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateAccountSnapshot"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLiquidatableCollateralRatio"
  ): TypedContractMethod<
    [_liquidatableCollateralRatio: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLiquidator"
  ): TypedContractMethod<[_liquidator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReward"
  ): TypedContractMethod<
    [_token: AddressLike, _manager: AddressLike, _periodLength: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUnlockDuration"
  ): TypedContractMethod<[_unlockDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnlocked"
  ): TypedContractMethod<
    [_doClaim: boolean, _unwrap: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapper"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AccountSnapshotTaken"
  ): TypedContractEvent<
    AccountSnapshotTakenEvent.InputTuple,
    AccountSnapshotTakenEvent.OutputTuple,
    AccountSnapshotTakenEvent.OutputObject
  >;
  getEvent(
    key: "AddRewardToken"
  ): TypedContractEvent<
    AddRewardTokenEvent.InputTuple,
    AddRewardTokenEvent.OutputTuple,
    AddRewardTokenEvent.OutputObject
  >;
  getEvent(
    key: "Claim"
  ): TypedContractEvent<
    ClaimEvent.InputTuple,
    ClaimEvent.OutputTuple,
    ClaimEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "DepositReward"
  ): TypedContractEvent<
    DepositRewardEvent.InputTuple,
    DepositRewardEvent.OutputTuple,
    DepositRewardEvent.OutputObject
  >;
  getEvent(
    key: "Liquidate"
  ): TypedContractEvent<
    LiquidateEvent.InputTuple,
    LiquidateEvent.OutputTuple,
    LiquidateEvent.OutputObject
  >;
  getEvent(
    key: "LossNotified"
  ): TypedContractEvent<
    LossNotifiedEvent.InputTuple,
    LossNotifiedEvent.OutputTuple,
    LossNotifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemoveRewardToken"
  ): TypedContractEvent<
    RemoveRewardTokenEvent.InputTuple,
    RemoveRewardTokenEvent.OutputTuple,
    RemoveRewardTokenEvent.OutputObject
  >;
  getEvent(
    key: "RewardsAccumulated"
  ): TypedContractEvent<
    RewardsAccumulatedEvent.InputTuple,
    RewardsAccumulatedEvent.OutputTuple,
    RewardsAccumulatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Unlock"
  ): TypedContractEvent<
    UnlockEvent.InputTuple,
    UnlockEvent.OutputTuple,
    UnlockEvent.OutputObject
  >;
  getEvent(
    key: "UpdateLiquidatableCollateralRatio"
  ): TypedContractEvent<
    UpdateLiquidatableCollateralRatioEvent.InputTuple,
    UpdateLiquidatableCollateralRatioEvent.OutputTuple,
    UpdateLiquidatableCollateralRatioEvent.OutputObject
  >;
  getEvent(
    key: "UpdateLiquidator"
  ): TypedContractEvent<
    UpdateLiquidatorEvent.InputTuple,
    UpdateLiquidatorEvent.OutputTuple,
    UpdateLiquidatorEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRewardToken"
  ): TypedContractEvent<
    UpdateRewardTokenEvent.InputTuple,
    UpdateRewardTokenEvent.OutputTuple,
    UpdateRewardTokenEvent.OutputObject
  >;
  getEvent(
    key: "UpdateUnlockDuration"
  ): TypedContractEvent<
    UpdateUnlockDurationEvent.InputTuple,
    UpdateUnlockDurationEvent.OutputTuple,
    UpdateUnlockDurationEvent.OutputObject
  >;
  getEvent(
    key: "UpdateWrapper"
  ): TypedContractEvent<
    UpdateWrapperEvent.InputTuple,
    UpdateWrapperEvent.OutputTuple,
    UpdateWrapperEvent.OutputObject
  >;
  getEvent(
    key: "UserDepositChange"
  ): TypedContractEvent<
    UserDepositChangeEvent.InputTuple,
    UserDepositChangeEvent.OutputTuple,
    UserDepositChangeEvent.OutputObject
  >;
  getEvent(
    key: "UserUnlockChange"
  ): TypedContractEvent<
    UserUnlockChangeEvent.InputTuple,
    UserUnlockChangeEvent.OutputTuple,
    UserUnlockChangeEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawUnlocked"
  ): TypedContractEvent<
    WithdrawUnlockedEvent.InputTuple,
    WithdrawUnlockedEvent.OutputTuple,
    WithdrawUnlockedEvent.OutputObject
  >;

  filters: {
    "AccountSnapshotTaken(address,uint256,uint256,uint256)": TypedContractEvent<
      AccountSnapshotTakenEvent.InputTuple,
      AccountSnapshotTakenEvent.OutputTuple,
      AccountSnapshotTakenEvent.OutputObject
    >;
    AccountSnapshotTaken: TypedContractEvent<
      AccountSnapshotTakenEvent.InputTuple,
      AccountSnapshotTakenEvent.OutputTuple,
      AccountSnapshotTakenEvent.OutputObject
    >;

    "AddRewardToken(address,address,uint256)": TypedContractEvent<
      AddRewardTokenEvent.InputTuple,
      AddRewardTokenEvent.OutputTuple,
      AddRewardTokenEvent.OutputObject
    >;
    AddRewardToken: TypedContractEvent<
      AddRewardTokenEvent.InputTuple,
      AddRewardTokenEvent.OutputTuple,
      AddRewardTokenEvent.OutputObject
    >;

    "Claim(address,address,uint256)": TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;
    Claim: TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;

    "Deposit(address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "DepositReward(address,uint256)": TypedContractEvent<
      DepositRewardEvent.InputTuple,
      DepositRewardEvent.OutputTuple,
      DepositRewardEvent.OutputObject
    >;
    DepositReward: TypedContractEvent<
      DepositRewardEvent.InputTuple,
      DepositRewardEvent.OutputTuple,
      DepositRewardEvent.OutputObject
    >;

    "Liquidate(uint256,uint256)": TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;
    Liquidate: TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;

    "LossNotified(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LossNotifiedEvent.InputTuple,
      LossNotifiedEvent.OutputTuple,
      LossNotifiedEvent.OutputObject
    >;
    LossNotified: TypedContractEvent<
      LossNotifiedEvent.InputTuple,
      LossNotifiedEvent.OutputTuple,
      LossNotifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemoveRewardToken(uint256,address)": TypedContractEvent<
      RemoveRewardTokenEvent.InputTuple,
      RemoveRewardTokenEvent.OutputTuple,
      RemoveRewardTokenEvent.OutputObject
    >;
    RemoveRewardToken: TypedContractEvent<
      RemoveRewardTokenEvent.InputTuple,
      RemoveRewardTokenEvent.OutputTuple,
      RemoveRewardTokenEvent.OutputObject
    >;

    "RewardsAccumulated(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RewardsAccumulatedEvent.InputTuple,
      RewardsAccumulatedEvent.OutputTuple,
      RewardsAccumulatedEvent.OutputObject
    >;
    RewardsAccumulated: TypedContractEvent<
      RewardsAccumulatedEvent.InputTuple,
      RewardsAccumulatedEvent.OutputTuple,
      RewardsAccumulatedEvent.OutputObject
    >;

    "RewardsDistributed(address,uint256,uint256,bool)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;

    "Unlock(address,uint256,uint256)": TypedContractEvent<
      UnlockEvent.InputTuple,
      UnlockEvent.OutputTuple,
      UnlockEvent.OutputObject
    >;
    Unlock: TypedContractEvent<
      UnlockEvent.InputTuple,
      UnlockEvent.OutputTuple,
      UnlockEvent.OutputObject
    >;

    "UpdateLiquidatableCollateralRatio(uint256)": TypedContractEvent<
      UpdateLiquidatableCollateralRatioEvent.InputTuple,
      UpdateLiquidatableCollateralRatioEvent.OutputTuple,
      UpdateLiquidatableCollateralRatioEvent.OutputObject
    >;
    UpdateLiquidatableCollateralRatio: TypedContractEvent<
      UpdateLiquidatableCollateralRatioEvent.InputTuple,
      UpdateLiquidatableCollateralRatioEvent.OutputTuple,
      UpdateLiquidatableCollateralRatioEvent.OutputObject
    >;

    "UpdateLiquidator(address)": TypedContractEvent<
      UpdateLiquidatorEvent.InputTuple,
      UpdateLiquidatorEvent.OutputTuple,
      UpdateLiquidatorEvent.OutputObject
    >;
    UpdateLiquidator: TypedContractEvent<
      UpdateLiquidatorEvent.InputTuple,
      UpdateLiquidatorEvent.OutputTuple,
      UpdateLiquidatorEvent.OutputObject
    >;

    "UpdateRewardToken(address,address,uint256)": TypedContractEvent<
      UpdateRewardTokenEvent.InputTuple,
      UpdateRewardTokenEvent.OutputTuple,
      UpdateRewardTokenEvent.OutputObject
    >;
    UpdateRewardToken: TypedContractEvent<
      UpdateRewardTokenEvent.InputTuple,
      UpdateRewardTokenEvent.OutputTuple,
      UpdateRewardTokenEvent.OutputObject
    >;

    "UpdateUnlockDuration(uint256)": TypedContractEvent<
      UpdateUnlockDurationEvent.InputTuple,
      UpdateUnlockDurationEvent.OutputTuple,
      UpdateUnlockDurationEvent.OutputObject
    >;
    UpdateUnlockDuration: TypedContractEvent<
      UpdateUnlockDurationEvent.InputTuple,
      UpdateUnlockDurationEvent.OutputTuple,
      UpdateUnlockDurationEvent.OutputObject
    >;

    "UpdateWrapper(address)": TypedContractEvent<
      UpdateWrapperEvent.InputTuple,
      UpdateWrapperEvent.OutputTuple,
      UpdateWrapperEvent.OutputObject
    >;
    UpdateWrapper: TypedContractEvent<
      UpdateWrapperEvent.InputTuple,
      UpdateWrapperEvent.OutputTuple,
      UpdateWrapperEvent.OutputObject
    >;

    "UserDepositChange(address,uint256,uint256)": TypedContractEvent<
      UserDepositChangeEvent.InputTuple,
      UserDepositChangeEvent.OutputTuple,
      UserDepositChangeEvent.OutputObject
    >;
    UserDepositChange: TypedContractEvent<
      UserDepositChangeEvent.InputTuple,
      UserDepositChangeEvent.OutputTuple,
      UserDepositChangeEvent.OutputObject
    >;

    "UserUnlockChange(address,uint256,uint256)": TypedContractEvent<
      UserUnlockChangeEvent.InputTuple,
      UserUnlockChangeEvent.OutputTuple,
      UserUnlockChangeEvent.OutputObject
    >;
    UserUnlockChange: TypedContractEvent<
      UserUnlockChangeEvent.InputTuple,
      UserUnlockChangeEvent.OutputTuple,
      UserUnlockChangeEvent.OutputObject
    >;

    "WithdrawUnlocked(address,uint256)": TypedContractEvent<
      WithdrawUnlockedEvent.InputTuple,
      WithdrawUnlockedEvent.OutputTuple,
      WithdrawUnlockedEvent.OutputObject
    >;
    WithdrawUnlocked: TypedContractEvent<
      WithdrawUnlockedEvent.InputTuple,
      WithdrawUnlockedEvent.OutputTuple,
      WithdrawUnlockedEvent.OutputObject
    >;
  };
}
