/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IJackRebalancePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "balanceOf"
      | "claim(address[],bool)"
      | "claim(address,bool)"
      | "claimable"
      | "deposit"
      | "depositReward"
      | "liquidate"
      | "totalSupply"
      | "unlock"
      | "unlockedBalanceOf"
      | "unlockingBalanceOf"
      | "updateAccountSnapshot"
      | "withdrawUnlocked"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claim"
      | "Deposit"
      | "DepositReward"
      | "Liquidate"
      | "Unlock"
      | "UserDepositChange"
      | "UserUnlockChange"
      | "WithdrawUnlocked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim(address[],bool)",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claim(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockedBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockingBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAccountSnapshot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnlocked",
    values: [boolean, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claim(address[],bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claim(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockedBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockingBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAccountSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnlocked",
    data: BytesLike
  ): Result;
}

export namespace ClaimEvent {
  export type InputTuple = [
    owner: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [owner: string, token: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    owner: AddressLike,
    reciever: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [owner: string, reciever: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    reciever: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRewardEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidateEvent {
  export type InputTuple = [liquidated: BigNumberish, baseGained: BigNumberish];
  export type OutputTuple = [liquidated: bigint, baseGained: bigint];
  export interface OutputObject {
    liquidated: bigint;
    baseGained: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockEvent {
  export type InputTuple = [
    owner: AddressLike,
    amount: BigNumberish,
    unlockAt: BigNumberish
  ];
  export type OutputTuple = [owner: string, amount: bigint, unlockAt: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
    unlockAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDepositChangeEvent {
  export type InputTuple = [
    owner: AddressLike,
    newDeposit: BigNumberish,
    loss: BigNumberish
  ];
  export type OutputTuple = [owner: string, newDeposit: bigint, loss: bigint];
  export interface OutputObject {
    owner: string;
    newDeposit: bigint;
    loss: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserUnlockChangeEvent {
  export type InputTuple = [
    owner: AddressLike,
    newUnlock: BigNumberish,
    loss: BigNumberish
  ];
  export type OutputTuple = [owner: string, newUnlock: bigint, loss: bigint];
  export interface OutputObject {
    owner: string;
    newUnlock: bigint;
    loss: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawUnlockedEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IJackRebalancePool extends BaseContract {
  connect(runner?: ContractRunner | null): IJackRebalancePool;
  waitForDeployment(): Promise<this>;

  interface: IJackRebalancePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  "claim(address[],bool)": TypedContractMethod<
    [tokens: AddressLike[], unwrap: boolean],
    [void],
    "nonpayable"
  >;

  "claim(address,bool)": TypedContractMethod<
    [token: AddressLike, unwrap: boolean],
    [void],
    "nonpayable"
  >;

  claimable: TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  depositReward: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  liquidate: TypedContractMethod<
    [maxAmount: BigNumberish, minBaseOut: BigNumberish],
    [[bigint, bigint] & { liquidated: bigint; baseOut: bigint }],
    "nonpayable"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  unlock: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  unlockedBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  unlockingBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { balance: bigint; unlockAt: bigint }],
    "view"
  >;

  updateAccountSnapshot: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawUnlocked: TypedContractMethod<
    [_claim: boolean, unwrap: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claim(address[],bool)"
  ): TypedContractMethod<
    [tokens: AddressLike[], unwrap: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim(address,bool)"
  ): TypedContractMethod<
    [token: AddressLike, unwrap: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositReward"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [maxAmount: BigNumberish, minBaseOut: BigNumberish],
    [[bigint, bigint] & { liquidated: bigint; baseOut: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlock"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockedBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockingBalanceOf"
  ): TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { balance: bigint; unlockAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateAccountSnapshot"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnlocked"
  ): TypedContractMethod<
    [_claim: boolean, unwrap: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Claim"
  ): TypedContractEvent<
    ClaimEvent.InputTuple,
    ClaimEvent.OutputTuple,
    ClaimEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "DepositReward"
  ): TypedContractEvent<
    DepositRewardEvent.InputTuple,
    DepositRewardEvent.OutputTuple,
    DepositRewardEvent.OutputObject
  >;
  getEvent(
    key: "Liquidate"
  ): TypedContractEvent<
    LiquidateEvent.InputTuple,
    LiquidateEvent.OutputTuple,
    LiquidateEvent.OutputObject
  >;
  getEvent(
    key: "Unlock"
  ): TypedContractEvent<
    UnlockEvent.InputTuple,
    UnlockEvent.OutputTuple,
    UnlockEvent.OutputObject
  >;
  getEvent(
    key: "UserDepositChange"
  ): TypedContractEvent<
    UserDepositChangeEvent.InputTuple,
    UserDepositChangeEvent.OutputTuple,
    UserDepositChangeEvent.OutputObject
  >;
  getEvent(
    key: "UserUnlockChange"
  ): TypedContractEvent<
    UserUnlockChangeEvent.InputTuple,
    UserUnlockChangeEvent.OutputTuple,
    UserUnlockChangeEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawUnlocked"
  ): TypedContractEvent<
    WithdrawUnlockedEvent.InputTuple,
    WithdrawUnlockedEvent.OutputTuple,
    WithdrawUnlockedEvent.OutputObject
  >;

  filters: {
    "Claim(address,address,uint256)": TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;
    Claim: TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;

    "Deposit(address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "DepositReward(address,uint256)": TypedContractEvent<
      DepositRewardEvent.InputTuple,
      DepositRewardEvent.OutputTuple,
      DepositRewardEvent.OutputObject
    >;
    DepositReward: TypedContractEvent<
      DepositRewardEvent.InputTuple,
      DepositRewardEvent.OutputTuple,
      DepositRewardEvent.OutputObject
    >;

    "Liquidate(uint256,uint256)": TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;
    Liquidate: TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;

    "Unlock(address,uint256,uint256)": TypedContractEvent<
      UnlockEvent.InputTuple,
      UnlockEvent.OutputTuple,
      UnlockEvent.OutputObject
    >;
    Unlock: TypedContractEvent<
      UnlockEvent.InputTuple,
      UnlockEvent.OutputTuple,
      UnlockEvent.OutputObject
    >;

    "UserDepositChange(address,uint256,uint256)": TypedContractEvent<
      UserDepositChangeEvent.InputTuple,
      UserDepositChangeEvent.OutputTuple,
      UserDepositChangeEvent.OutputObject
    >;
    UserDepositChange: TypedContractEvent<
      UserDepositChangeEvent.InputTuple,
      UserDepositChangeEvent.OutputTuple,
      UserDepositChangeEvent.OutputObject
    >;

    "UserUnlockChange(address,uint256,uint256)": TypedContractEvent<
      UserUnlockChangeEvent.InputTuple,
      UserUnlockChangeEvent.OutputTuple,
      UserUnlockChangeEvent.OutputObject
    >;
    UserUnlockChange: TypedContractEvent<
      UserUnlockChangeEvent.InputTuple,
      UserUnlockChangeEvent.OutputTuple,
      UserUnlockChangeEvent.OutputObject
    >;

    "WithdrawUnlocked(address,uint256)": TypedContractEvent<
      WithdrawUnlockedEvent.InputTuple,
      WithdrawUnlockedEvent.OutputTuple,
      WithdrawUnlockedEvent.OutputObject
    >;
    WithdrawUnlocked: TypedContractEvent<
      WithdrawUnlockedEvent.InputTuple,
      WithdrawUnlockedEvent.OutputTuple,
      WithdrawUnlockedEvent.OutputObject
    >;
  };
}
