/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IJackTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aToken"
      | "baseToken"
      | "collateralRatio"
      | "convertToUnwrapped"
      | "convertToWrapped"
      | "currentBaseTokenPrice"
      | "getCurrentNav"
      | "isBaseTokenPriceValid"
      | "isUnderCollateral"
      | "lastPermissionedPrice"
      | "leverageRatio"
      | "maxLiquidatable"
      | "maxMintableXToken"
      | "maxMintableXTokenWithIncentive"
      | "maxMintableaToken"
      | "maxRedeemableXToken"
      | "maxRedeemableaToken"
      | "mint"
      | "redeem"
      | "totalBaseToken"
      | "xAVAXLeverageRatio"
      | "xToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProtocolSettle"): EventFragment;

  encodeFunctionData(functionFragment: "aToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collateralRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertToUnwrapped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToWrapped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentBaseTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentNav",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBaseTokenPriceValid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUnderCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPermissionedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLiquidatable",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableXToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableXTokenWithIncentive",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableaToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeemableXToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeemableaToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBaseToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xAVAXLeverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "aToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToUnwrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToWrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBaseTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentNav",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBaseTokenPriceValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUnderCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPermissionedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLiquidatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableXToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableXTokenWithIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeemableXToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeemableaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xAVAXLeverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xToken", data: BytesLike): Result;
}

export namespace ProtocolSettleEvent {
  export type InputTuple = [price: BigNumberish, aNav: BigNumberish];
  export type OutputTuple = [price: bigint, aNav: bigint];
  export interface OutputObject {
    price: bigint;
    aNav: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IJackTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): IJackTreasury;
  waitForDeployment(): Promise<this>;

  interface: IJackTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aToken: TypedContractMethod<[], [string], "view">;

  baseToken: TypedContractMethod<[], [string], "view">;

  collateralRatio: TypedContractMethod<[], [bigint], "view">;

  convertToUnwrapped: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  convertToWrapped: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  currentBaseTokenPrice: TypedContractMethod<[], [bigint], "view">;

  getCurrentNav: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { baseNav: bigint; aNav: bigint; xNav: bigint }
    ],
    "view"
  >;

  isBaseTokenPriceValid: TypedContractMethod<[], [boolean], "view">;

  isUnderCollateral: TypedContractMethod<[], [boolean], "view">;

  lastPermissionedPrice: TypedContractMethod<[], [bigint], "view">;

  leverageRatio: TypedContractMethod<[], [bigint], "view">;

  maxLiquidatable: TypedContractMethod<
    [newCollateralRatio: BigNumberish, incentiveRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxaTokenLiquidatable: bigint }],
    "view"
  >;

  maxMintableXToken: TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxXTokenMintable: bigint }],
    "view"
  >;

  maxMintableXTokenWithIncentive: TypedContractMethod<
    [newCollateralRatio: BigNumberish, incentiveRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxXTokenMintable: bigint }],
    "view"
  >;

  maxMintableaToken: TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxaTokenMintable: bigint }],
    "view"
  >;

  maxRedeemableXToken: TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxXTokenRedeemable: bigint }],
    "view"
  >;

  maxRedeemableaToken: TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxaTokenRedeemable: bigint }],
    "view"
  >;

  mint: TypedContractMethod<
    [baseIn: BigNumberish, recipient: AddressLike, option: BigNumberish],
    [[bigint, bigint] & { aTokenOut: bigint; xTokenOut: bigint }],
    "nonpayable"
  >;

  redeem: TypedContractMethod<
    [aTokenIn: BigNumberish, xTokenIn: BigNumberish, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  totalBaseToken: TypedContractMethod<[], [bigint], "view">;

  xAVAXLeverageRatio: TypedContractMethod<[], [bigint], "view">;

  xToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collateralRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToUnwrapped"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToWrapped"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentBaseTokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentNav"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { baseNav: bigint; aNav: bigint; xNav: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBaseTokenPriceValid"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUnderCollateral"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPermissionedPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "leverageRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxLiquidatable"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish, incentiveRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxaTokenLiquidatable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableXToken"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxXTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableXTokenWithIncentive"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish, incentiveRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxXTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxMintableaToken"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseIn: bigint; maxaTokenMintable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxRedeemableXToken"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxXTokenRedeemable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxRedeemableaToken"
  ): TypedContractMethod<
    [newCollateralRatio: BigNumberish],
    [[bigint, bigint] & { maxBaseOut: bigint; maxaTokenRedeemable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [baseIn: BigNumberish, recipient: AddressLike, option: BigNumberish],
    [[bigint, bigint] & { aTokenOut: bigint; xTokenOut: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [aTokenIn: BigNumberish, xTokenIn: BigNumberish, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBaseToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xAVAXLeverageRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProtocolSettle"
  ): TypedContractEvent<
    ProtocolSettleEvent.InputTuple,
    ProtocolSettleEvent.OutputTuple,
    ProtocolSettleEvent.OutputObject
  >;

  filters: {
    "ProtocolSettle(uint256,uint256)": TypedContractEvent<
      ProtocolSettleEvent.InputTuple,
      ProtocolSettleEvent.OutputTuple,
      ProtocolSettleEvent.OutputObject
    >;
    ProtocolSettle: TypedContractEvent<
      ProtocolSettleEvent.InputTuple,
      ProtocolSettleEvent.OutputTuple,
      ProtocolSettleEvent.OutputObject
    >;
  };
}
