/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Upgradeable } from "./ERC20Upgradeable";
export type { IERC20Upgradeable } from "./IERC20Upgradeable";
